<style>
table {  font-family: arial, sans-serif;  border-collapse: collapse;  width: 100%;  margin-top: 30px;}
td, th {  border: 1px solid #dddddd;  text-align: left;  padding: 8px;  }
tr:nth-child(even) { background-color: #dddddd; }
.post-id{width:2%} .post-name{width:30%}

</style>

<table>
  <tr>
    <th class="user-id">Id</th>
    <th class="user-name">Name</th>
    <th class="user-type">Type Employee</th>
    <th class="user-description">Description</th>
    <th class="tags">Tags</th>
  </tr>
    <?php
        foreach ($block->getUserCollection() as $key=>$user){
            echo '<tr>
                    <td>'.$user->getUserId().'</td>
                    <td>'.$user->getName().'</td>
                    <td>'.$user->getTypeEmployee().'</td>
                    <td>'.$user->getDescriptionEmployee().'</td>
                    <td>'.$user->getTags().'</td>
                  </tr>';
        }
    ?>
</table>

</body>
</html>